apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartpm-backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
    spec:
      containers:
      - name: backend
        image: smartpm-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://smartpm-mongo:27017/smartpm"
        - name: JWT_SECRET
          value: "votre_super_secret_jwt"
---
apiVersion: v1
kind: Service
metadata:
  name: smartpm-backend
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    app: backend
