apiVersion: v1
kind: Secret
metadata:
  name: smartpm-secrets
type: Opaque
data:
  # echo -n "super-secret-key-aerospace-99" | base64
  JWT_SECRET: c3VwZXItc2VjcmV0LWtleS1hZXJvc3BhY2UtOTk=
  # echo -n "AIzaSyDcTvGBqIOolROAMBPxdp8F8fTanPB0zAQ" | base64
  GEMINI_API_KEY: QUl6YVN5RGNUdkdCcUlPb2xST0FNQlB4ZHA4RjhmVGFuUEIwekFR
